import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { DatabaseEngine } from './_DatabaseEngine';
import AdminFooter from './AdminFooter';

const toNumber = v => typeof v === 'number' ? v : Number(String(v || '0').replace(/[^0-9.-]/g, '')) || 0;
const isToday = raw => { const d = new Date(raw || 0); return !Number.isNaN(d.getTime()) && d.toDateString() === new Date().toDateString(); };
const isMonth = raw => { const d = new Date(raw || 0); const n = new Date(); return !Number.isNaN(d.getTime()) && d.getMonth() === n.getMonth() && d.getFullYear() === n.getFullYear(); };
const total = orders => orders.reduce((sum,o)=>sum+toNumber(o.payable_total??o.grand_total??o.total_amount??o.payableTotal),0);

export default function AdminAnalyticsScreen(){
  const [loading,setLoading]=useState(true); const [orders,setOrders]=useState([]); const [reps,setReps]=useState([]); const [products,setProducts]=useState([]); const [messages,setMessages]=useState([]);
  useEffect(()=>{(async()=>{const [o,r,p,m]=await Promise.all([DatabaseEngine.getAllOrders(),DatabaseEngine.getAllReps(),DatabaseEngine.getCatalog(),DatabaseEngine.getAdminMessages()]); setOrders(o||[]); setReps(r||[]); setProducts(p||[]); setMessages(m||[]); setLoading(false);})()},[]);
  const today=useMemo(()=>orders.filter(o=>isToday(o.created_at||o.localTimestamp)),[orders]); const month=useMemo(()=>orders.filter(o=>isMonth(o.created_at||o.localTimestamp)),[orders]); const low=products.filter(p=>toNumber(p.stock)<10).length; const open=messages.filter(m=>String(m.status||'Open').toLowerCase()!=='closed').length;
  return <SafeAreaView style={styles.container}><View style={styles.header}><Text style={styles.title}>📊 Analytics</Text><Text style={styles.sub}>Business snapshot across orders, reps, stock and messages.</Text></View><ScrollView contentContainerStyle={styles.scroll}>{loading?<View style={styles.empty}><ActivityIndicator color="#2563EB"/><Text style={styles.emptySub}>Loading analytics...</Text></View>:<><View style={styles.grid}><Metric label="Today Orders" value={today.length}/><Metric label="Today Value" value={`₦${total(today).toLocaleString()}`}/><Metric label="Month Orders" value={month.length}/><Metric label="Month Value" value={`₦${total(month).toLocaleString()}`}/><Metric label="Total Reps" value={reps.length}/><Metric label="Products" value={products.length}/><Metric label="Low Stock" value={low}/><Metric label="Open Messages" value={open}/></View><View style={styles.panel}><Text style={styles.panelTitle}>Insights</Text><Text style={styles.insight}>• {low} product(s) are low stock and need attention.</Text><Text style={styles.insight}>• {open} open admin message(s) require replies/follow-up.</Text><Text style={styles.insight}>• Today order value is ₦{total(today).toLocaleString()}.</Text></View></>}</ScrollView><AdminFooter/></SafeAreaView>
}
function Metric({label,value}){return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#F8FAFC'},header:{padding:16,backgroundColor:'#EFF6FF'},title:{fontSize:24,fontWeight:'900',color:'#1E3A8A'},sub:{color:'#64748B',fontSize:12,lineHeight:18,marginTop:4},scroll:{padding:16,paddingBottom:95},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},metric:{width:'48%',backgroundColor:'#FFF',borderWidth:1,borderColor:'#DBEAFE',borderRadius:18,padding:14},metricValue:{color:'#0F172A',fontSize:20,fontWeight:'900'},metricLabel:{color:'#64748B',fontSize:10,fontWeight:'900',textTransform:'uppercase',marginTop:4},panel:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0',borderRadius:20,padding:16,marginTop:16},panelTitle:{color:'#0F172A',fontSize:16,fontWeight:'900',marginBottom:8},insight:{color:'#334155',fontSize:12,lineHeight:20},empty:{backgroundColor:'#FFF',borderRadius:20,padding:26,borderWidth:1,borderColor:'#DBEAFE',alignItems:'center'},emptySub:{color:'#64748B',marginTop:8}})
